# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='critical_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
