# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_medicine_critical_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='monthyl_usage',
            field=models.IntegerField(default=1000),
        ),
    ]
