# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_medicine_monthyl_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='monthyl_usage',
            new_name='monthly_usage',
        ),
    ]
